// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_calendar_data;

namespace web_calendar_data.Migrations
{
    [DbContext(typeof(WebCalendarDbContext))]
    [Migration("20201017200312_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("web_calendar_data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@mail.com",
                            FirstName = "FN1",
                            LastName = "LN1",
                            PasswordHash = new byte[] { 1, 2, 3, 4, 5 },
                            Salt = new byte[] { 1, 2 }
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@mail.com",
                            FirstName = "FN2",
                            LastName = "LN2",
                            PasswordHash = new byte[] { 1, 2, 3, 4, 5 },
                            Salt = new byte[] { 1, 2 }
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@mail.com",
                            FirstName = "FN3",
                            LastName = "LN3",
                            PasswordHash = new byte[] { 1, 2, 3, 4, 5 },
                            Salt = new byte[] { 1, 2 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
